version: '3.8'

services:
  backend:
    build:
      context: ./ApptituteBackend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ApptituteBackend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db
    networks:
      - internal_net

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - CI=true
    networks:
      - internal_net


networks:
  internal_net:
    driver: bridge