# Generated by Django 5.1.1 on 2024-09-30 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000, verbose_name='Question')),
                ('A', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Option A')),
                ('B', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Option B')),
                ('C', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Option C')),
                ('D', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Option D')),
                ('correct_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone Number')),
                ('ctc', models.CharField(max_length=255, verbose_name='CTC')),
                ('role', models.CharField(max_length=255, verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_selected_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=255, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='test_app.question')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='test_app.usercandidate')),
            ],
        ),
    ]
