# Generated by Django 5.1.1 on 2024-09-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quest_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Question Id'),
        ),
    ]
