# Generated by Django 5.1.1 on 2024-10-03 06:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_question_quest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_formatted_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='usercandidate',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usercandidate',
            name='phone',
            field=models.CharField(max_length=255, unique=True, verbose_name='Phone Number'),
        ),
    ]
