# Generated by Django 5.1.1 on 2024-10-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_question_question_formatted_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('candidate', 'question')},
        ),
    ]
